dnaStrand = "TGCGGACGATATTTAAAGATGTCCCGATGTACCTAAGAGACAATAGACACACGAAGCGCGACATCTCAGTCTCGGGGGACACCTGCAAGCCTCAGCAATCCCATTCTGGCATAGCTCCAAGGTAGGTCTGTCATTGTAGGACAGATATCGCCTTCGTTGAGATTGACGCAAGTATCACTACCAAATGCATCACAGGAACTTGAACTGGTATGGTCGTCAGGGTTGATATCATGAAGATGAGTCACATGATCGCCTCCGCCGTCCTTACCCCACTTCACCCGGTTGTTTCAAGGCGATGCATTCTCCAAGCGATGTTAACAGGCTCCCGCCGTGAGAGCATGGGAGTATATATGGAGACTTCTGACCACGACCGTAAGGGTCGATTGTGCTGGTTTTAAACGTCGTTTGGGTCAGCGTCTTCCCCTACGGTTTACCTGGGAGCCACATATTGAGAGTAGGTCCTCGGTGGGCAGACAGACCGTCCGCTACAGGGGAGTGTGAGTCCACCCTTGACGACGGCCATATTAATCCGCGGCGCCTTTATCGAACGCTTCCTCTCGCTCTTGGCTGTCAGATCGGCTGCATCCTCCTTACACCGATAGCCGCGCTATGATCCCAGCTCTCAGCTAGCGGCCCAGACTTCGGTGATTTTTAGGGCCCACAATTACCACGATCCAGTGAGCAGAGTGGGCATTGGTCTTAGCCTGTTGTCGGTCGTAGCCGATTCCTAATCCCTACCTAGCCGTTTCACAGGCCAATTGTTGGCAACTCAACACAACACCCCTATCTTGTCGCTTCGATCCCATGCCGCAGATAAAGCGGAGTCTAGGATTAAGTTGGTCTGCAAGCAGAAGGAGTGTGTCTTCTCCTATTGCGTGTGTAGACCCAGCA"

#This function will take a given strand of DNA and count the nucleotides A, C, G, T and output the count.
def nucCnt (D):
    nucA = D.count('A')
    nucC = D.count('C')
    nucG = D.count('G')
    nucT = D.count('T')
    print('\n',"Nucleotide A Count:",nucA,'\n',"Nucleotide C Count:", nucC,'\n',"Nucleotide G Count:", nucG,'\n', "Nucleotide T Count:",nucT)


nucCnt(dnaStrand) #this will apply the funtion to the variable of stored DNA above.