dnaStrand = "TGCGGACGATATTTAAAGATGTCCCGATGTACCTAAGAGACAATAGACACACGAAGCGCGACATCTCAGTCTCGGGGGACACCTGCAAGCCTCAGCAATCCCATTCTGGCATAGCTCCAAGGTAGGTCTGTCATTGTAGGACAGATATCGCCTTCGTTGAGATTGACGCAAGTATCACTACCAAATGCATCACAGGAACTTGAACTGGTATGGTCGTCAGGGTTGATATCATGAAGATGAGTCACATGATCGCCTCCGCCGTCCTTACCCCACTTCACCCGGTTGTTTCAAGGCGATGCATTCTCCAAGCGATGTTAACAGGCTCCCGCCGTGAGAGCATGGGAGTATATATGGAGACTTCTGACCACGACCGTAAGGGTCGATTGTGCTGGTTTTAAACGTCGTTTGGGTCAGCGTCTTCCCCTACGGTTTACCTGGGAGCCACATATTGAGAGTAGGTCCTCGGTGGGCAGACAGACCGTCCGCTACAGGGGAGTGTGAGTCCACCCTTGACGACGGCCATATTAATCCGCGGCGCCTTTATCGAACGCTTCCTCTCGCTCTTGGCTGTCAGATCGGCTGCATCCTCCTTACACCGATAGCCGCGCTATGATCCCAGCTCTCAGCTAGCGGCCCAGACTTCGGTGATTTTTAGGGCCCACAATTACCACGATCCAGTGAGCAGAGTGGGCATTGGTCTTAGCCTGTTGTCGGTCGTAGCCGATTCCTAATCCCTACCTAGCCGTTTCACAGGCCAATTGTTGGCAACTCAACACAACACCCCTATCTTGTCGCTTCGATCCCATGCCGCAGATAAAGCGGAGTCTAGGATTAAGTTGGTCTGCAAGCAGAAGGAGTGTGTCTTCTCCTATTGCGTGTGTAGACCCAGCA"

#This function will take a given strand of DNA and count the nucleotides A, C, G, T and output the count.
def nucCnt (D):
    nucA = D.count('A')
    nucC = D.count('C')
    nucG = D.count('G')
    nucT = D.count('T')
    print(nucA, nucC, nucG, nucT)


nucCnt(dnaStrand) #this will apply the funtion to the variable of stored DNA above.