dnaStrand = "TGCGGACGATATTTAAAGATGTCCCGATGTACCTAAGAGACAATAGACACACGAAGCGCGACATCTCAGTCTCGGGGGACACCTGCAAGCCTCAGCAATCCCATTCTGGCATAGCTCCAAGGTAGGTCTGTCATTGTAGGACAGATATCGCCTTCGTTGAGATTGACGCAAGTATCACTACCAAATGCATCACAGGAACTTGAACTGGTATGGTCGTCAGGGTTGATATCATGAAGATGAGTCACATGATCGCCTCCGCCGTCCTTACCCCACTTCACCCGGTTGTTTCAAGGCGATGCATTCTCCAAGCGATGTTAACAGGCTCCCGCCGTGAGAGCATGGGAGTATATATGGAGACTTCTGACCACGACCGTAAGGGTCGATTGTGCTGGTTTTAAACGTCGTTTGGGTCAGCGTCTTCCCCTACGGTTTACCTGGGAGCCACATATTGAGAGTAGGTCCTCGGTGGGCAGACAGACCGTCCGCTACAGGGGAGTGTGAGTCCACCCTTGACGACGGCCATATTAATCCGCGGCGCCTTTATCGAACGCTTCCTCTCGCTCTTGGCTGTCAGATCGGCTGCATCCTCCTTACACCGATAGCCGCGCTATGATCCCAGCTCTCAGCTAGCGGCCCAGACTTCGGTGATTTTTAGGGCCCACAATTACCACGATCCAGTGAGCAGAGTGGGCATTGGTCTTAGCCTGTTGTCGGTCGTAGCCGATTCCTAATCCCTACCTAGCCGTTTCACAGGCCAATTGTTGGCAACTCAACACAACACCCCTATCTTGTCGCTTCGATCCCATGCCGCAGATAAAGCGGAGTCTAGGATTAAGTTGGTCTGCAAGCAGAAGGAGTGTGTCTTCTCCTATTGCGTGTGTAGACCCAGCA"

#This function will take a given strand of DNA and count the nucleotides A, C, G, T and output the count.
def nucCnt (D):
    nucTotal = len(D)
    nucAP = round(((D.count('A')/nucTotal)*100), 1) 
    nucCP = round(((D.count('C')/nucTotal)*100), 1)
    nucGP = round(((D.count('G')/nucTotal)*100), 1)
    nucTP = round(((D.count('T')/nucTotal)*100), 1)
    
    print("A:",nucAP, "C:",nucCP, "G:", nucGP, "T:",nucTP)


nucCnt(dnaStrand) #this will apply the funtion to the variable of stored DNA above.
